# Numpy

In [2]:
import numpy as np

### THE BASICS

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# get dimension
b.ndim


2

In [7]:
a.ndim

1

In [8]:
# get shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
#GET type
a.dtype

dtype('int32')

In [20]:
#Size
a.size

3

In [22]:
a.itemsize

4

### Accessing specific Elements change Rows, columns

In [26]:
a = np.array([[1,2,3,4,5,6,7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get specific elemnts
a[1, 5]

13

In [30]:
#get row
a [0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
#get column
a[ : , 3]

array([ 4, 11])

In [38]:
#Change element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [44]:
b = np.array([[1,2], [3,4], [5,6], [7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    
    [[7, 8, 9],
     [10, 11, 12]]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
arr.shape

(2, 2, 3)

### Intializing differnt type of array

In [51]:
#zero
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
#Ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.ones((2,3), dtype="int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [63]:
#Any other numbers 
np.full((2,3), 44)

array([[44, 44, 44],
       [44, 44, 44]])

In [65]:
np.full(a.shape,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [69]:
#RAndom NUmbers
np.random.rand(2,3)

array([[0.22985024, 0.01924477, 0.48372304, 0.54420605],
       [0.3642873 , 0.78814897, 0.46920073, 0.52340749]])

In [81]:
np.random.randint(8, size=(2,3))

array([[4, 5, 2],
       [1, 1, 7]])

In [83]:
np.random.randint(-6, 8, size=(5,3))

array([[ 0, -2, -6],
       [-6,  1, -5],
       [-2,  1,  3],
       [ 5, -3, -5],
       [-3,  2,  6]])

In [89]:
#Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 4  , axis = 0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [115]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### BE careful when coping array

In [129]:
a = np.array((1,2,3))
b=a
b

a[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [131]:
a = np.array((1,2,3))
b=a.copy()
b

a[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]


## MAthematics

In [136]:
a = np.array((1,2,3))
print(a)

[1 2 3]


In [138]:
a + 2

array([3, 4, 5])

In [140]:
a - 2

array([-1,  0,  1])

In [142]:
b = np.array((1,2,3))
a+b

array([2, 4, 6])

In [144]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Linear Algebra

In [153]:
a = np.ones((2,3))
print(a)

b = np.full((3,4), 4)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [157]:
np.matmul(a,b)

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [159]:
# 1D vector
v = np.array([1, 2, 3])

# 2D matrix
A = np.array([[1, 2], [3, 4]])

In [161]:
A.T   # or np.transpose(A)


array([[1, 3],
       [2, 4]])

### Statistics

In [185]:
stat = np.array((2,3,4))
print(stat)

[2 3 4]


In [175]:
np.max(stat)

4

In [177]:
np.min(stat)

2

In [181]:
np.sum(stat, axis=0)

9

### Reorganizing Array

In [202]:
before = np.array([[1,2,3,4], [4,5,6,7]])
print(before)
print(before.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


In [208]:
before = np.array([[1,2,3,4], [4,5,6,7]])
print(before)
after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [4 5 6 7]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [212]:
# Vertically stack 
v1 = np.array([1,2,3])
v2 = np.array([1,9,4])

np.vstack((v1,v2))

array([[1, 2, 3],
       [1, 9, 4]])

In [214]:
# Horizontal stack 
v1 = np.array([1,2,3])
v2 = np.array([1,9,4])

np.hstack((v1,v2))

array([1, 2, 3, 1, 9, 4])