**Numpy Tutorial**


In [5]:
import numpy as np

Sure! Here are the **names of basic NumPy queries** that you can use without the performance details:

---

### **1. Array Creation**
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eye()`
- `np.random.rand()`
- `np.random.randint()`
- `np.arange()`
- `np.linspace()`

---

### **2. Array Properties**
- `ndim` 
- `shape`
- `size`
- `dtype`

---

### **3. Array Operations**
- `+` (Addition)
- `-` (Subtraction)
- `*` (Multiplication)
- `/` (Division)
- `**` (Exponentiation)

---

### **4. Aggregation Functions**
- `np.sum()`
- `np.mean()`
- `np.min()`
- `np.max()`
- `np.std()`
- `np.prod()`
- `np.argmin()`
- `np.argmax()`

---

### **5. Indexing and Slicing**
- `arr[<index>]`
- `arr[start:end]`
- `arr[start:end:step]`
- `arr[:, <column>]`
- `arr[<row>, <column>]`

---

### **6. Reshaping and Transposing**
- `np.reshape()`
- `np.transpose()`
- `arr.T`

---

### **7. Joining Arrays**
- `np.concatenate()`
- `np.vstack()`
- `np.hstack()`

---

### **8. Splitting Arrays**
- `np.array_split()`
- `np.split()`

---

### **9. Searching and Sorting**
- `np.sort()`
- `np.argsort()`
- `np.where()`
- `np.nonzero()`

---

### **10. Filtering**
- `arr[arr > <value>]`
- `np.extract()`

---

These are the core **NumPy queries** you can use in different operations. Let me know if you need more!

In [10]:
myarr = np.array([3,6,7,78], np.int64)
print(myarr)


[ 3  6  7 78]


In [12]:
myarr

array([ 3,  6,  7, 78], dtype=int64)

In [5]:
myarr[0]

3

In [6]:
myarr.shape

(4,)

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


***Array Creation Conversion from other python structures***

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
arr2 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                 [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
                 # ... more rows
                ])

In [16]:
print(arr2.ndim)    # Dimensions


2


In [17]:
print(arr2.shape)   # Shape of 2D array


(3, 10)


In [18]:
print(arr2.size)    # Total number of elements in 3D


30


In [19]:
print(arr2.dtype)   # Data type of elements in arr2

int32


In [20]:
np.zeros((5,5))  # 5x5 array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((2,3))   # 2x3 array of ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((3,3),8)    # 3x3 array filled with 8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [23]:
np.random.rand(4, 5)   # 4x5 array of random floats

array([[0.88256172, 0.3676753 , 0.84755824, 0.54561128, 0.90978537],
       [0.83968557, 0.94368979, 0.38132406, 0.4025159 , 0.0749898 ],
       [0.72216791, 0.74369995, 0.91918315, 0.54577275, 0.02635131],
       [0.85667951, 0.74722158, 0.43476058, 0.44878055, 0.04246582]])

In [24]:
np.eye(5)              # 5x5 Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arange(0, 100, 4)  # 0 to 95 with step 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [26]:
np.linspace(0, 100, 10)  # 6 equally spaced points between 0 and 10

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [27]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print(a + b)       # Element-wise addition
print(a - b)       # Element-wise subtraction
print(a * b)       # Element-wise multiplication
print(a / b)       # Element-wise division
print(a ** 2)      # Square of each element

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[ 1  4  9 16 25]


In [28]:
arr = np.arange(1, 101)  # 1D array with 100 elements
print(arr)
print(arr.sum())           # Sum of all elements
print(arr.min())           # Minimum value
print(arr.max())           # Maximum value
print(arr.mean())          # Mean (average)
print(arr.std())           # Standard deviati

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
5050
1
100
50.5
28.86607004772212


In [29]:
arr = np.arange(1, 101)    # 1D array of 100 elements

In [30]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
print(arr[10])            # 11th element
print(arr[-1])            # Last element
print(arr[10:20])         # Slice from index 10 to 19

11
100
[11 12 13 14 15 16 17 18 19 20]


In [32]:
arr2 = np.random.randint(1, 100, (10, 10))   # 10x10 array
print(arr2)

[[48  6  6 24 42 15 87 49 49 40]
 [45 62 48 67 44 53 25 39 15 97]
 [53 47 22 37 92 66  6 79  8 63]
 [ 5 24 76 17 23 45 82 36 52 80]
 [ 6 63  7 60 18 76  2 48  2 34]
 [30 67 26 90 25 77 59 15 21 78]
 [43 58 34 51 19 67 36 50 86 55]
 [12 81 16 98 98  7 71  7 40 42]
 [86 49 77 39 83 64 39 32 74 68]
 [30 57 10 51 43 28 10 45 33 50]]


In [33]:
print(arr2[0, 0])         # Element in row 0, column 0

48


In [34]:
print(arr2[:, 1])         # All rows, column 1

[ 6 62 47 24 63 67 58 81 49 57]


In [35]:
# Copy (independent)
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)   # Original not changed

[1 2 3]


In [36]:
# View (linked)
c = a.view()
c[0] = 200
print(a)   # Original changes

[200   2   3]


In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))            # Join 1D arrays
             

array([1, 2, 3, 4, 5, 6])

In [38]:
np.vstack((a, b))                 # Stack vertically


array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.hstack((a, b))    #horizontally

array([1, 2, 3, 4, 5, 6])

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6])

np.array_split(arr, 3)      # Split into 3 parts

[array([1, 2]), array([3, 4]), array([5, 6])]

In [82]:
arr = np.array([6, 3, 1, 7, 2])

print(np.where(arr == 7))          # Find index where value is 7


(array([3], dtype=int64),)


In [84]:
print(np.sort(arr))    

[1 2 3 6 7]


In [86]:
arr = np.array([1, 2, 3, 4, 5])

filter_arr = arr > 2
print(arr[filter_arr])       # [3 4 5]

[3 4 5]
